### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by 2560p** [ZsomborHajzer/Project-3-BB#5]
Please, start on cleaning up the code. Re-read all the written comments, rewrite them if they are not clear enough.
Remove any commented code, fix indentation.
I suppose we can start now / tomorrow, so everyone is quite finished on Friday.

Thank you all!! :)

**Comment by ZsomborHajzer** [comment]
I have removed unnecessary code, made sure naming conventions are up to documentation standards and made sure that there are easy to read comments in the code.

**Comment by timothyadewale** [comment]
I have worked on it, unnecessary code was removed, comments added to meet conventions standards

**Comment by 2560p** [comment]
The fixes were made! The code looks clean and awaits the merge to the `main` branch.

Thanks everybody for the cooperation! 🫡
